"""
Regression tests for Volume Profile and Order Flow indicators.

All tests use frozen fixture data (tests/fixtures/volume_profile_ohlcv.csv
and tests/fixtures/order_flow_ohlcv.csv) generated by scripts/generate_fixtures.py.
No live network calls.
"""
import os
import pytest
import pandas as pd

FIXTURES_DIR = os.path.join(os.path.dirname(__file__), 'fixtures')

# ── Expected values (computed by scripts/generate_fixtures.py) ──────────────
EXPECTED_POC = 149.4051
EXPECTED_VAH = 157.263
EXPECTED_VAL = 145.4761
EXPECTED_CUM_DELTA_LAST = 9_667_644.529655589


@pytest.fixture(scope='module')
def vp_df():
    path = os.path.join(FIXTURES_DIR, 'volume_profile_ohlcv.csv')
    return pd.read_csv(path, index_col='Date', parse_dates=True)


@pytest.fixture(scope='module')
def of_df():
    path = os.path.join(FIXTURES_DIR, 'order_flow_ohlcv.csv')
    return pd.read_csv(path, index_col='Date', parse_dates=True)


# ---------------------------------------------------------------------------
# Volume Profile
# ---------------------------------------------------------------------------

@pytest.mark.regression
def test_volume_profile_poc_regression(vp_df):
    from src.analytics.trading_indicators import compute_volume_profile
    result = compute_volume_profile(vp_df)
    assert result['poc'] == pytest.approx(EXPECTED_POC, abs=0.10)


@pytest.mark.regression
def test_volume_profile_vah_regression(vp_df):
    from src.analytics.trading_indicators import compute_volume_profile
    result = compute_volume_profile(vp_df)
    assert result['vah'] == pytest.approx(EXPECTED_VAH, abs=0.10)


@pytest.mark.regression
def test_volume_profile_val_regression(vp_df):
    from src.analytics.trading_indicators import compute_volume_profile
    result = compute_volume_profile(vp_df)
    assert result['val'] == pytest.approx(EXPECTED_VAL, abs=0.10)


@pytest.mark.regression
def test_volume_profile_vah_gt_poc_gt_val(vp_df):
    from src.analytics.trading_indicators import compute_volume_profile
    result = compute_volume_profile(vp_df)
    assert result['val'] < result['poc'] < result['vah']


@pytest.mark.regression
def test_volume_profile_signal_valid(vp_df):
    from src.analytics.trading_indicators import compute_volume_profile
    result = compute_volume_profile(vp_df)
    assert result['signal'] in ('inside', 'outside')


@pytest.mark.regression
def test_volume_profile_returns_required_keys(vp_df):
    from src.analytics.trading_indicators import compute_volume_profile
    result = compute_volume_profile(vp_df)
    for key in ('poc', 'vah', 'val', 'signal', 'traces', 'layout'):
        assert key in result


# ---------------------------------------------------------------------------
# Order Flow
# ---------------------------------------------------------------------------

@pytest.mark.regression
def test_order_flow_cumulative_delta_regression(of_df):
    import numpy as np
    ranges = (of_df['High'] - of_df['Low']).clip(lower=1e-9)
    buy_ratio = (of_df['Close'] - of_df['Low']) / ranges
    delta = (2 * buy_ratio - 1) * of_df['Volume']
    cum_delta_last = float(delta.cumsum().iloc[-1])
    assert cum_delta_last == pytest.approx(EXPECTED_CUM_DELTA_LAST, rel=0.01)


@pytest.mark.regression
def test_order_flow_no_nan_cumulative_delta(of_df):
    import numpy as np
    ranges = (of_df['High'] - of_df['Low']).clip(lower=1e-9)
    buy_ratio = (of_df['Close'] - of_df['Low']) / ranges
    delta = (2 * buy_ratio - 1) * of_df['Volume']
    cum = delta.cumsum()
    assert not cum.isnull().any()


@pytest.mark.regression
def test_order_flow_signal_valid(of_df):
    from src.analytics.trading_indicators import compute_order_flow
    result = compute_order_flow(of_df)
    assert result['signal'] in ('bullish', 'bearish', 'neutral')


@pytest.mark.regression
def test_order_flow_divergence_fields_present(of_df):
    from src.analytics.trading_indicators import compute_order_flow
    result = compute_order_flow(of_df)
    assert 'divergence' in result
    div = result['divergence']
    assert 'detected' in div
    assert 'price_slope' in div
    assert 'vol_slope' in div


@pytest.mark.regression
def test_order_flow_returns_traces_and_layout(of_df):
    from src.analytics.trading_indicators import compute_order_flow
    result = compute_order_flow(of_df)
    assert 'traces' in result
    assert 'layout' in result
